server:
  port: 8888
  bind: 0.0.0.0
  log: 'WebhookEventServer.log'
  secret: streng_geheim
  # GitHub API request info
  token: 9e7aaa62c5a619d5852e872551ffad79e4f27348 
  github_api: 'https://api.github.com'
  owner: jefeish
  organization: jchallenge1

# list the Webhook events to respond to
webhooks:
  # events list from - https://developer.github.com/webhooks/

  # this section is for the 'unit test'
  - event: repository
    description: 'UNIT TESTING'
    payload_attrs:
      - action: deleted
      - repository.name: code-repo
    actions:
      task:
        - create_issue
      cmd:
        - echo "[$(date)] UNIT TESTING, event='repository', action='deleted'" >> ./test.txt

  - event: issues
    description: 'Webhook event, issue opened'
    # the payload_attr acts as a filter option
    payload_attrs:
      - action: opened
    actions:
      task:
        - notification
      
  - event: repository
    description: 'create an issue when a repository gets deleted'
    payload_attrs:
      - action: deleted
    actions:
      task:
        - create_issue
